// Generato da import-pharmacy-registry.ts — non modificare a mano.
import type { AtlasPlaceRegistryEntry } from "./atlas-registry.js";

export const ATLAS_PHARMACY_PLACES_VT_DATA: AtlasPlaceRegistryEntry[] = [
  {
    id: "place-pharmacy-ministero-10101",
    name: "ANTICA FARMACIA SACCARELLI SAS DEL DOTT. F. CATOCCI E C.",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "ACQUAPENDENTE",
    address: "Piazza Girolamo Fabrizio, 15 - 01021 - ACQUAPENDENTE",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10101", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10067",
    name: "FARMACIA CATOCCI SNC DI FABIO E CARLO CATOCCI",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "ACQUAPENDENTE",
    address: "Via Igino Gini 2/a - 01021 - ACQUAPENDENTE",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10067", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10111",
    name: "SEGUINO SEBASTIANO",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "ARLENA DI CASTRO",
    address: "Via Vittorio Emanuele, 128 - 01010 - ARLENA DI CASTRO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10111", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10122",
    name: "BIGIOTTI FRANCESCO E ANDREA SNC",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "BAGNOREGIO",
    address: "Piazza Trento e Trieste, 8 - 01022 - BAGNOREGIO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10122", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10090",
    name: "POSATI GIOVANNA",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "BARBARANO ROMANO",
    address: "Viale Quattro Novembre, 19 - 01010 - BARBARANO ROMANO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10090", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10087",
    name: "MASTRODICASA RICCARDO",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "BASSANO IN TEVERINA",
    address: "Via Giuseppe Mazzini, 3 - 01030 - BASSANO IN TEVERINA",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10087", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10114",
    name: "BASSANO ROMANO SAS",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "BASSANO ROMANO",
    address: "Via Leonardo da Vinci, 5 - 01030 - BASSANO ROMANO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10114", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-20580",
    name: "Farmabassano Srl",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "BASSANO ROMANO",
    address: "Piazza Vittorio Emanuele, 11 - 01030 - BASSANO ROMANO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "20580", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10120",
    name: "Franceschini Dr.ssa Elena",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "BLERA",
    address: "Via Roma, 109 - 01010 - BLERA",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10120", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10143",
    name: "LANZI SNC DI FABRIZIO E FABIO LANZI",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "BOLSENA",
    address: "Via Gramsci, 38 - 01023 - BOLSENA",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10143", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10077",
    name: "FRANCESCHINI VEZIO LEONIL",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "BOMARZO",
    address: "Piazza B. Buozzi, 6 - 01020 - BOMARZO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10077", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10117",
    name: "D'Erme Alessandro",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "CALCATA",
    address: "Piazza Risorgimento, 1 - 01030 - CALCATA",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10117", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10106",
    name: "FARMACIADICANEPINASRL",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "CANEPINA",
    address: "Piazza DEI CADUTI, 18 - 01030 - CANEPINA",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10106", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-20301",
    name: "FARMACIA ETRURIA snc",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "CANINO",
    address: "Viale dell' UnitÃ  d' Italia, 2 - 01011 - CANINO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "20301", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10084",
    name: "LUCIANI GIUSEPPE",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "CANINO",
    address: "Via Giuseppe Garibaldi, 30 - 01011 - CANINO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10084", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10086",
    name: "Farmacia Marenghi S.a.s. Di Marenghi Dr. Pietro - Marenghi Dott.ssa Beatrice & C.",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "CAPODIMONTE",
    address: "Via Guglielmo Marconi, 70 - 01010 - CAPODIMONTE",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10086", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10145",
    name: "Farmacapranica Di Finocchi Silvia",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "CAPRANICA",
    address: "Via via Giacomo Matteotti, snc - 01012 - CAPRANICA",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10145", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10073",
    name: "FARMACIA MORERA SNC DEI DR.RI ANTONIO E LUDOVICA MORERA",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "CAPRANICA",
    address: "Via Padre Luigi Maria Monti, 7 - 13 - 01012 - CAPRANICA",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10073", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10089",
    name: "farmacia la paradisa di giuseppe e antonella rossi snc",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "CAPRAROLA",
    address: "Via caduti sul lavoro, 39 - 01032 - CAPRAROLA",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10089", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10082",
    name: "LANDI MASCAGNA DI FARMACIA LA PARADISA DI G. E A. ROSSI",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "CAPRAROLA",
    address: "Via F. Nicolai, 141 - 01032 - CAPRAROLA",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10082", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10066",
    name: "CASSINI RENZO",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "CARBOGNANO",
    address: "Via Fontanavecchia, 38 - 01030 - CARBOGNANO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10066", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10144",
    name: "RUPES SNC DELLE DR.SSE A.M. COCCIA E I STEFANI",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "CASTEL SANT'ELIA",
    address: "Via Roma, 14 - 01030 - CASTEL SANT'ELIA",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10144", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10128",
    name: "MAVEZ SRL",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "CASTIGLIONE IN TEVERINA",
    address: "Via ORVIETANA, 5 - 01024 - CASTIGLIONE IN TEVERINA",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10128", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10105",
    name: "TESI SILVIA",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "CELLENO",
    address: "Piazza della Repubblica - 01020 - CELLENO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10105", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10121",
    name: "ABBATELLI CARLA",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "CELLERE",
    address: "Via Marconi, 13 - 01010 - CELLERE",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10121", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10091",
    name: "COMUNALE N. 1 CIVITA CASTELLANA",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "CIVITA CASTELLANA",
    address: "Via F. Petrarca snc - 01033 - CIVITA CASTELLANA",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10091", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10092",
    name: "COMUNALE N.2 CIVITA CASTELLANA",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "CIVITA CASTELLANA",
    address: "Via V. Ferretti, 95 - 01033 - CIVITA CASTELLANA",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10092", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10074",
    name: "FARMACIA FILIZZOLA",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "CIVITA CASTELLANA",
    address: "Via Di Corte, 3-5 - 01033 - CIVITA CASTELLANA",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10074", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-20985",
    name: "La Farmacia Di Borghetto Srl",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "CIVITA CASTELLANA",
    address: "Via Giuseppe Taschini, 11 - 01033 - CIVITA CASTELLANA",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "20985", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-17125",
    name: "SASSACCI DELLA DR.SSA ANNA MARIA VERSACE",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "CIVITA CASTELLANA",
    address: "Via Terni, 23 - 01033 - CIVITA CASTELLANA",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "17125", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10102",
    name: "OMNIAFARMA SNC",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "CIVITELLA D'AGLIANO",
    address: "Piazza Cardinal M. Dolci, 21 - 01020 - CIVITELLA D'AGLIANO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10102", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10130",
    name: "SANGIORGI SNC",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "CORCHIANO",
    address: "Via Civita Castellana, 11/13 - 01030 - CORCHIANO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10130", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-20638",
    name: "FARMACIA FALERI SAS - Dott.ssa Stefania De Vito & C.",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "FABRICA DI ROMA",
    address: "Via FALERINA, 23 - 01034 - FABRICA DI ROMA",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "20638", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10127",
    name: "Farmacia Liberati S.r.l.",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "FABRICA DI ROMA",
    address: "Via Roma, 77 - 01034 - FABRICA DI ROMA",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10127", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-18657",
    name: "Farmafabrica Srl",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "FABRICA DI ROMA",
    address: "Via A. Ligabue, SNC - 01034 - FABRICA DI ROMA",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "18657", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10110",
    name: "LUPO CARMELA",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "FALERIA",
    address: "Via S. Giuliano, snc - 01030 - FALERIA",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10110", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10065",
    name: "FARMACIA CASALI SAS DEL DR. EDOARDO CASALI & C.",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "FARNESE",
    address: "Via Principe Amedeo, 126 - 01010 - FARNESE",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10065", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10071",
    name: "CONTI ELDA",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "GALLESE",
    address: "Largo Tronsarelli, 41 - 01035 - GALLESE",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10071", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10072",
    name: "FARMACIA BASSANELLI DARIA",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "GRADOLI",
    address: "Via INDIPENDENZA, 15 - 01010 - GRADOLI",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10072", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10141",
    name: "CECCARINI DR.SSA FEDERICA",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "GRAFFIGNANO",
    address: "Piazza Umberto I, 28 - 01020 - GRAFFIGNANO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10141", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10138",
    name: "CIUCCI DOTT.SSA CECCARINI VALENTINA",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "GRAFFIGNANO",
    address: "Via LUIGI CORI, 7 - 01020 - GRAFFIGNANO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10138", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10078",
    name: "FARMACIA FRATERNALE SNC",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "GROTTE DI CASTRO",
    address: "Via Vittorio Veneto, 4/G - 01025 - GROTTE DI CASTRO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10078", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10068",
    name: "CERULLI SNC DEI DOTTORI MARIA CONSUELO E ALBERTO CERULLI",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "ISCHIA DI CASTRO",
    address: "Via Caporossi, 15 - 01010 - ISCHIA DI CASTRO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10068", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10135",
    name: "FIMO FARMACEUTICA S.A.S. DI MOCINI FILIPPO E C.",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "LATERA",
    address: "Via Roma, 19 - 01010 - LATERA",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10135", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-21150",
    name: "Farmacia Comunale di Lubriano",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "LUBRIANO",
    address: "Via Via 1 Maggio, 6 - 01020 - LUBRIANO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "21150", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10098",
    name: "PERINELLI ROMEO",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "LUBRIANO",
    address: "Via G. Marconi, 1 - 01020 - LUBRIANO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10098", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10123",
    name: "DE BLASIO LIVIA",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "MARTA",
    address: "Via Tuscania, 4/a - 01010 - MARTA",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10123", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10118",
    name: "BORBOTTI GIUSEPPINA E PAOLA SNC",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "MONTALTO DI CASTRO",
    address: "Via Aurelia, 30 - 01014 - MONTALTO DI CASTRO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10118", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-18248",
    name: "COMUNALE MONTALTO DI CASTRO",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "MONTALTO DI CASTRO",
    address: "Via del Palombaro, 11 - 01014 - MONTALTO DI CASTRO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "18248", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10107",
    name: "MAZZONI VIRGINIA",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "MONTALTO DI CASTRO",
    address: "Piazza delle Mimose, 15 - 01010 - MONTALTO DI CASTRO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10107", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10056",
    name: "MINELLI DAVID",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "MONTE ROMANO",
    address: "Via Vittorio Emanuele, 45 - 01010 - MONTE ROMANO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10056", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10134",
    name: "BIANCHI SNC",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "MONTEFIASCONE",
    address: "Via Cardinal Salotti 48 - 01027 - MONTEFIASCONE",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10134", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-20819",
    name: "Farmacia Iori Dr. Lucia",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "MONTEFIASCONE",
    address: "Via tartarola, 91 - 01027 - MONTEFIASCONE",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "20819", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10112",
    name: "FARMACIE BRAGUTI SRL",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "MONTEFIASCONE",
    address: "Via Verentana, 8 - 01027 - MONTEFIASCONE",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10112", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10103",
    name: "TERRACINA CARLA",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "MONTEFIASCONE",
    address: "Via Zepponami, 265/a - 01020 - MONTEFIASCONE",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10103", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10099",
    name: "FARMACIA DIDO S.R.L..",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "MONTEROSI",
    address: "Via Roma, 51 - 01030 - MONTEROSI",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10099", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10129",
    name: "NEPI DI SINI GIANLUCA E C. SNC",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "NEPI",
    address: "Via Roma, 19 - 01036 - NEPI",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10129", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-16696",
    name: "PHARMANEPI SRL",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "NEPI",
    address: "Via Francesco Gianelli, snc - 01036 - NEPI",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "16696", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10126",
    name: "COZZOLINO NUNZIA",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "ONANO",
    address: "Piazza Umberto I, 4 - 01010 - ONANO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10126", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10136",
    name: "farmacia oriolo della farmacia Vetralla sas",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "ORIOLO ROMANO",
    address: "Piazza Porta Romana, 15 - 01010 - ORIOLO ROMANO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10136", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10057",
    name: "BARBAGLI CARLO FELICE",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "ORTE",
    address: "Via Giuseppe Garibaldi, 52 - 01028 - ORTE",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10057", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10069",
    name: "COMUNALE ORTE",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "ORTE",
    address: "Piazza del Popolo, 15 - 01028 - ORTE",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10069", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-21275",
    name: "Farmacia Comunale 2",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "ORTE",
    address: "Via Amerina, 19/21 - 01028 - ORTE",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "21275", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10061",
    name: "BIANCHI MARIA RITA",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "PIANSANO",
    address: "Via Roma, 16 - 01010 - PIANSANO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10061", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-17835",
    name: "DISPENSARIO FARMACEUTICO",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "PROCENO",
    address: "Corso Regina Margherita, 50 - 01020 - PROCENO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "17835", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10131",
    name: "CENTRALE DEI DOTT. GUERRA FABIO E FERRAZZA MARCO SRL",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "RONCIGLIONE",
    address: "Viale della Resistenza, 39 - 01037 - RONCIGLIONE",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10131", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10058",
    name: "S.BARTOLOMEO DI LISTANTE DOTT. SAVERIO",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "RONCIGLIONE",
    address: "Via della Resistenza, snc - 01037 - RONCIGLIONE",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10058", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10116",
    name: "FARMACIA MENICHELLI SAS DEL DR GIUSEPPE MENICHELLI & C",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "SAN LORENZO NUOVO",
    address: "Piazza Europa, 3 - 01020 - SAN LORENZO NUOVO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10116", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10142",
    name: "BELATI  ZAGOREO s.a.s.",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "SORIANO NEL CIMINO",
    address: "Piazza Vittorio Emanuele, 19 - 22 - 01038 - SORIANO NEL CIMINO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10142", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-19799",
    name: "FARMACIA DEL CIMINO  di PETROSELLI SAS Dr Antonio Rositani",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "SORIANO NEL CIMINO",
    address: "Via Viale Cesare Battisti, 51 - 01038 - SORIANO NEL CIMINO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "19799", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10095",
    name: "MUSCOLINO DARIO E C. SAS",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "SORIANO NEL CIMINO",
    address: "Via E. Monaci, 96 - 01038 - SORIANO NEL CIMINO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10095", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-20332",
    name: "FARMACIA SANT'ANTONIO SNC DEL DR. MICHELE PIANELLI & C.",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "SUTRI",
    address: "Via MORONE, 1 B/C - 01015 - SUTRI",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "20332", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10108",
    name: "FARMACIA SUTRI S.N.C. DI MARINI AGOSTINI MONICA E ANDREA",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "SUTRI",
    address: "Piazza del Comune, 22 - 01015 - SUTRI",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10108", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10113",
    name: "FARMACIA DEL CORSO SAS DEL DR. VIRGINIO DE ANGELIS & C",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "TARQUINIA",
    address: "Corso Vittorio Emanuele, 33-37 - 01016 - TARQUINIA",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10113", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10137",
    name: "Farmacia Greco del Dr Sapere Agostino & C.Snc",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "TARQUINIA",
    address: "Via Andrea Doria, 55 - 01016 - TARQUINIA",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10137", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-21210",
    name: "MUNICIPALIZZATA N. 3",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "TARQUINIA",
    address: "Via Dei Tarquiniensi, snc - 01016 - TARQUINIA",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "21210", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10093",
    name: "MUNICIPALIZZATA N.1 TARQUINIA",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "TARQUINIA",
    address: "Viale Luigi Dasti, 7 - 01016 - TARQUINIA",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10093", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10094",
    name: "MUNICIPALIZZATA N.2 TARQUINIA",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "TARQUINIA",
    address: "Via A. Moro - 01016 - TARQUINIA",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10094", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10096",
    name: "BRUNI ALESSANDRA",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "TESSENNANO",
    address: "Piazza Umberto I, 19 - 01010 - TESSENNANO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10096", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10125",
    name: "Farmacia  Ventura Srl",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "TUSCANIA",
    address: "Piazza Italia, 11 - 01017 - TUSCANIA",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10125", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-19828",
    name: "farmacia perinelli sas del dr raul francesco perinelli e  c",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "TUSCANIA",
    address: "Via 6 febbraio 1971, snc - 01017 - TUSCANIA",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "19828", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10133",
    name: "Saliola Bucelli Marco",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "TUSCANIA",
    address: "Via Tarquinia, 53 - 01017 - TUSCANIA",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10133", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10062",
    name: "BIGIOTTI M.P. SNC DI MARCO BIGIOTTI & C.",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "VALENTANO",
    address: "Piazza Cavour, 12 - 01018 - VALENTANO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10062", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10109",
    name: "Farmacia Polidori sas di Polidori Agnese e C",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "VALLERANO",
    address: "Piazza Alberto xerry de caro, 14 - 01030 - VALLERANO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10109", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10083",
    name: "FARMACIA SAN LANNO SAS DI ALESSANDRA PAOLELLI",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "VASANELLO",
    address: "Via San Lanno, 53-55 - 01030 - VASANELLO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10083", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10139",
    name: "FARMACIA MODICA DI REEDY FRANCESCO, MARIA LUNELLA E MAURIZIO SNC",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "VEJANO",
    address: "Via UMBERTO I, 53 - 01010 - VEJANO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10139", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-17196",
    name: "COMUNALE TRE CROCI IN CONCESSIONE A FARMACIA ZONGHI E CERRI SNC",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "VETRALLA",
    address: "Piazza Europa, 66 - 01010 - VETRALLA",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "17196", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-19856",
    name: "Farmacia Tre B Snc Dei Dr.ri Francesco Braguti, Anna Livia Bevilacqua E Matteo Bernardi",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "VETRALLA",
    address: "Piazza Vittorio Emanuele 7 - 01019 - VETRALLA",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "19856", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10140",
    name: "VETRALLA Sas DELLA DR.SSA STEFANIA MENGHI E C.",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "VETRALLA",
    address: "Via S. Michele snc, snc - 01019 - VETRALLA",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10140", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10115",
    name: "ZONGHI F. & CERRI D. SNC",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "VETRALLA",
    address: "Via Cassia, 38/a - 01013 - VETRALLA",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10115", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10085",
    name: "LUPI SNC",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "VIGNANELLO",
    address: "Via Roma, 2/d - 01039 - VIGNANELLO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10085", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10097",
    name: "PALAGGI GIUSEPPE",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "VILLA SAN GIOVANNI IN TUSCIA",
    address: "Piazza Savoia, snc - 01010 - VILLA SAN GIOVANNI IN TUSCIA",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10097", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10060",
    name: "BLASI LUIGIA",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "VITERBO",
    address: "Viale Fiume, 6 - 01100 - VITERBO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10060", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-16413",
    name: "DEI CAPPUCCINI S.R.L.",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "VITERBO",
    address: "Via Vicenza, 40/A - 01100 - VITERBO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "16413", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10064",
    name: "Farmacia Carlini S.a.S",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "VITERBO",
    address: "Via Della Sapienza, 5/7 - 01100 - VITERBO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10064", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-21151",
    name: "Farmacia Comunale Riello",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "VITERBO",
    address: "Via Galvani, 38 - 01100 - VITERBO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "21151", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-19443",
    name: "FARMACIA DEI PAPI SNC DELLE DR.SSE MARIA LAURA PAOLI E MARINA MANGANOZZI",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "VITERBO",
    address: "Via Cassia Nord, 13a-13c - 01100 - VITERBO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "19443", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10075",
    name: "FARMACIA DEL CARMINE SAS DELLA DR.SSA VALERIA CIANCHELLI & C",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "VITERBO",
    address: "Via CASTELLO VETULONIA, 20 - 01100 - VITERBO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10075", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10104",
    name: "FARMACIA DEL PILASTRO S.A.S. DELLA DOTT.SSA PATRIZIA PUCCI E C.",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "VITERBO",
    address: "Via Minciotti, 35 - 01100 - VITERBO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10104", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10076",
    name: "Farmacia del Sacrario srl",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "VITERBO",
    address: "Piazza dei caduti, 12/13/14/15 - 01100 - VITERBO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10076", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-19402",
    name: "Farmacia Gabriele Rossi  s.a.s del Dr. Gabriele Rossi",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "VITERBO",
    address: "Via Madre Teresa Di Calcutta, 2/c - 01100 - VITERBO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "19402", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-20572",
    name: "Farmacia il Murialdo Srl",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "VITERBO",
    address: "Via Monti Cimini, 15 - 01100 - VITERBO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "20572", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10119",
    name: "FARMACIA PETROSELLI S.A.S. DELLA DR.SSA MARIA TERESA PETROSELLI",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "VITERBO",
    address: "Via Carlo Catteneo, 30/D - 01100 - VITERBO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10119", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10124",
    name: "FARMACIA RICCARDI S.R.L.",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "VITERBO",
    address: "Via della Palazzina, 195/199 - 01100 - VITERBO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10124", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10063",
    name: "Farmacia Rossi srl",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "VITERBO",
    address: "Largo Africa, 14 - 01100 - VITERBO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10063", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10080",
    name: "FARMACIA VIALE TRIESTE SRL",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "VITERBO",
    address: "Viale Trieste, 36/A - 01100 - VITERBO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10080", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10070",
    name: "FRANCIGENA SRL - COMUNALE S.BARBARA",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "VITERBO",
    address: "Via Porsenna, snc - 01100 - VITERBO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10070", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-17098",
    name: "FRANCIGENA SRL -COMUNALE LA QUERCIA",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "VITERBO",
    address: "PIAZZA CAMPO GRAZIANO, 37 - 01030 - VITERBO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "17098", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10079",
    name: "GALIANO SNC DI PALMUCCI ALESSANDRO E PALMUCCI FRANCESCO",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "VITERBO",
    address: "Via Garibaldi , 1 - 01100 - VITERBO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10079", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-16414",
    name: "MONTALBOLDI SNC",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "VITERBO",
    address: "Piazza Giuseppe Verdi, 1/a - 01100 - VITERBO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "16414", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10088",
    name: "MORELLI DOTT. FABIANO",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "VITERBO",
    address: "Via PUGLIA, 15 - 01100 - VITERBO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10088", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10132",
    name: "SAN MARTINO DI NATALINI P",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "VITERBO",
    address: "Piazza M. Buratti, 2/3 - 01030 - VITERBO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10132", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  },
  {
    id: "place-pharmacy-ministero-10100",
    name: "RICCI MARI DI LOREDANA MARI",
    placeType: "pharmacy",
    territoryId: "IT-VT",
    municipality: "VITORCHIANO",
    address: "Via A. Manzoni, 15/F - 01030 - VITORCHIANO",
    status: "active",
    primarySourceId: "src-ministero-pharmacy-it",
    externalRefs: { ministero: { cim: "10100", url: "https://www.dati.salute.gov.it/sites/default/files/opendata/FRM_FARMA_5_20260816.csv" } },
    notes: "Registro Ministero della Salute, osservato 2026-08-16",
  }
];
